spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/userData}  # MongoDB URI (replace with your actual URI)

  mvc:
    throw-exception-if-no-handler-found: true  # Optional: to throw exception if no handler found

  # Springdoc configuration for OpenAPI/Swagger
  doc:
    api:
      paths-to-match: /, /api/**

server:
  port: 8081
