spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://MYSQL1001.site4now.net:3306/db_aaee7a_product}
    username: ${JDBC_DATABASE_USERNAME:aaee7a_product}
    password: ${JDBC_DATABASE_PASSWORD:Clw9090**}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
springdoc:
  pathsToMatch: /, /api/**
